esphome:
    name: hot_tub_temp
    platform: ESP8266
    board: nodemcuv2
    comment: Hot Tub Temp
  
<<: !include ./includes/common.yaml

dallas:
  - pin: D3 #GPIO0

sensor:
  - platform: dallas
    index: 0
    name: "Hot Tub Temp"