esphome:
  name: outdoor_light_sensor
  platform: ESP8266
  board: nodemcuv2
  comment: Outdoor Light Sensor

<<: !include includes/common.yaml

i2c:
  frequency: 400kHz

sensor:
  - platform: bh1750
    name: "Outdoor Light Level"
    address: 0x23