esphome:
  name: plants
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: "BulockHA"
  password: !secret ha_wifi_password

  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plants Fallback Hotspot"
    password: !secret local_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:

sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:66:39:BD'
    temperature:
      name: "Foyer Temperature"
      unit_of_measurement: "°F"
    moisture:
      name: "Foyer Plant Moisture"
    illuminance:
      name: "Foyer Illuminance"
    conductivity:
      name: "Foyer Plant Soil Conductivity"
    battery_level:
      name: "Foyer Plant Sensor Battery Level"

  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:62:D4:B0'
    temperature:
      name: "Loft Temperature"
      unit_of_measurement: "°F"
    moisture:
      name: "Loft Plant Moisture"
    illuminance:
      name: "Loft Illuminance"
    conductivity:
      name: "Loft Plant Soil Conductivity"
    battery_level:
      name: "Loft Plant Sensor Battery Level"

  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:62:D4:B0'
    temperature:
      name: "Office Temperature"
      unit_of_measurement: "°F"
    moisture:
      name: "Aloe Plant Moisture"
    illuminance:
      name: "Office Illuminance"
    conductivity:
      name: "Aloe Plant Soil Conductivity"
    battery_level:
      name: "Aloe Plant Sensor Battery Level"