esphome:
  name: plants
  platform: ESP32
  board: esp32doit-devkit-v1
  comment: Plant Data Collector

<<: !include common.yaml

esp32_ble_tracker:
  scan_parameters:
    active: false

sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:66:39:BD'
    temperature:
      name: "Foyer Temperature"
    moisture:
      name: "Foyer Plant Moisture"
    illuminance:
      name: "Foyer Illuminance"
    conductivity:
      name: "Foyer Plant Soil Conductivity"
    battery_level:
      name: "Foyer Plant Sensor Battery Level"

  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:62:D4:B0'
    temperature:
      name: "Loft Temperature"
    moisture:
      name: "Loft Plant Moisture"
    illuminance:
      name: "Loft Illuminance"
    conductivity:
      name: "Loft Plant Soil Conductivity"
    battery_level:
      name: "Loft Plant Sensor Battery Level"

  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:62:D4:CF'
    temperature:
      name: "Office Temperature"
    moisture:
      name: "Aloe Plant Moisture"
    illuminance:
      name: "Office Illuminance"
    conductivity:
      name: "Aloe Plant Soil Conductivity"
    battery_level:
      name: "Aloe Plant Sensor Battery Level"
