esphome:
  name: pool_plugs
  platform: ESP8266
  board: esp01_1m
  comment: Pool Plugs

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      then:
        - switch.toggle: relay_left
        - switch.toggle: relay_right

switch:
  - platform: gpio
    name: "Left plug"
    pin: GPIO14
    id: relay_left
    on_turn_on:
      - light.turn_on: blue_led
    on_turn_off:
      - light.turn_off: blue_led
  - platform: gpio
    name: "Right plug"
    pin: GPIO16
    id: relay_right
    on_turn_on:
      - light.turn_on: green_led
    on_turn_off:
      - light.turn_off: green_led

output:
  - platform: gpio
    pin: GPIO5
    inverted: True
    id: green_led_gpio
  - platform: gpio
    pin: GPIO13
    inverted: True
    id: blue_led_gpio

light:
  - platform: binary
    name: "Green LED"
    id: green_led
    output: green_led_gpio
  - platform: binary
    name: "Blue LED"
    id: blue_led
    output: blue_led_gpio